### ISSUE TITLE
Consider moving to swaywm GitHub org

### ISSUE THREAD

**Issue by ddevault** [swaywm/hsroots#1]
I've established the [swaywm GitHub org](https://github.com/swaywm) and moved wlroots there. We have discussed maintaining wlroots API wrappers within the swaywm organization - if you'd like, I can add you and we can host it there. Of course, the project would remain yours and you'd still have complete autonomy over it.

**Comment by Ongy** [comment]
Sure.
What do we have to do, to get this done?

**Comment by ddevault** [comment]
I added you to the org - all you have to do is accept the invite and move the repo. Thanks!

**Comment by Ongy** [comment]
Moved, so I'll close this.

**Comment by ddevault** [comment]
Thanks!
